// Client-safe integration definitions — no server dependencies

export const INTEGRATIONS = [
  // ── Content ─────────────────────────────────────────────────────────────
  {
    service: "youtube",
    name: "YouTube",
    category: "Content",
    description: "Fetch trending videos, search content, get transcripts",
    authMethod: "api_key" as const,
    keyLabel: "YouTube Data API v3 Key",
    color: "#FF0000",
    capabilities: ["Fetch trending videos", "Search videos", "Get transcripts"],
    docsUrl: "https://console.cloud.google.com/apis/library/youtube.googleapis.com",
  },
  {
    service: "wordpress",
    name: "WordPress",
    category: "Content",
    description: "Create posts, manage pages, upload media to your site",
    authMethod: "api_key" as const,
    keyLabel: "WordPress Application Password (username:app_password)",
    color: "#21759B",
    capabilities: ["Create posts", "Update pages", "Upload media"],
    docsUrl: "https://developer.wordpress.org/rest-api/",
  },
  {
    service: "spotify",
    name: "Spotify",
    category: "Content",
    description: "Search tracks, get playlist data, fetch artist info",
    authMethod: "api_key" as const,
    keyLabel: "Spotify Client ID:Client Secret",
    color: "#1DB954",
    capabilities: ["Search tracks", "Get playlists", "Fetch artist info"],
    docsUrl: "https://developer.spotify.com/documentation/web-api",
  },
  // ── Communication ────────────────────────────────────────────────────────
  {
    service: "gmail",
    name: "Gmail",
    category: "Communication",
    description: "Send emails, read inbox, search messages",
    authMethod: "api_key" as const,
    keyLabel: "Gmail credential: user@gmail.com:app-password",
    extraFields: [
      {
        key: "chatId",
        label: "Recipient Email Address",
        placeholder: "you@example.com",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#EA4335",
    capabilities: ["Send emails", "Read inbox", "Search messages"],
    docsUrl: "https://myaccount.google.com/apppasswords",
  },
  {
    service: "slack",
    name: "Slack",
    category: "Communication",
    description: "Send messages, post to channels, notify teams",
    authMethod: "api_key" as const,
    keyLabel: "Slack Bot Token (xoxb-...)",
    extraFields: [
      {
        key: "chatId",
        label: "Channel ID or Name",
        placeholder: "#general or C0XXXXXXX",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#4A154B",
    capabilities: ["Send messages", "Post to channels", "List channels"],
    docsUrl: "https://api.slack.com/apps",
  },
  {
    service: "telegram",
    name: "Telegram",
    category: "Communication",
    description: "Send messages and alerts via Telegram Bot API",
    authMethod: "api_key" as const,
    keyLabel: "Telegram Bot Token (from @BotFather)",
    extraFields: [
      {
        key: "chatId",
        label: "Chat ID / Username",
        placeholder: "@username or numeric chat ID (e.g. 123456789)",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#2CA5E0",
    capabilities: ["Send messages", "Send photos", "Notify channels"],
    docsUrl: "https://core.telegram.org/bots#botfather",
  },
  {
    service: "discord",
    name: "Discord",
    category: "Communication",
    description: "Post messages to Discord channels via webhooks or bot",
    authMethod: "api_key" as const,
    keyLabel: "Webhook URL (https://discord.com/api/webhooks/...) or Bot Token",
    extraFields: [
      {
        key: "chatId",
        label: "Channel ID (only if using Bot Token, not needed for Webhook URL)",
        placeholder: "123456789012345678",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#5865F2",
    capabilities: ["Send messages", "Post embeds", "Manage channels"],
    docsUrl: "https://discord.com/developers/applications",
  },
  {
    service: "twilio",
    name: "Twilio",
    category: "Communication",
    description: "Send SMS and make voice calls programmatically",
    authMethod: "api_key" as const,
    keyLabel: "Twilio Account SID:Auth Token",
    extraFields: [
      {
        key: "fromNumber",
        label: "Your Twilio Phone Number (E.164 format)",
        placeholder: "+14155552671",
        type: "text",
      },
      {
        key: "chatId",
        label: "Recipient Phone Number (E.164 format)",
        placeholder: "+919876543210",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#F22F46",
    capabilities: ["Send SMS", "Make calls", "WhatsApp API"],
    docsUrl: "https://console.twilio.com",
  },
  // ── Social Media ─────────────────────────────────────────────────────────
  {
    service: "twitter",
    name: "Twitter / X",
    category: "Social",
    description: "Post tweets, read timeline, search trends",
    authMethod: "api_key" as const,
    keyLabel: "X (Twitter) API Bearer Token",
    color: "#000000",
    capabilities: ["Post tweets", "Read timeline", "Search tweets"],
    docsUrl: "https://developer.twitter.com/en/portal/dashboard",
  },
  {
    service: "instagram",
    name: "Instagram",
    category: "Social",
    description: "Publish content, read insights via Meta Graph API",
    authMethod: "api_key" as const,
    keyLabel: "Instagram Graph API Access Token",
    color: "#E1306C",
    capabilities: ["Post photos", "Read insights", "Get media"],
    docsUrl: "https://developers.facebook.com/docs/instagram-api",
  },
  {
    service: "linkedin",
    name: "LinkedIn",
    category: "Social",
    description: "Post updates, share content, manage company pages",
    authMethod: "api_key" as const,
    keyLabel: "LinkedIn OAuth 2.0 Access Token",
    color: "#0A66C2",
    capabilities: ["Post updates", "Share articles", "Company pages"],
    docsUrl: "https://www.linkedin.com/developers/apps",
  },
  {
    service: "tiktok",
    name: "TikTok",
    category: "Social",
    description: "Fetch viral videos, trends, and creator analytics",
    authMethod: "api_key" as const,
    keyLabel: "TikTok Developer API Key",
    color: "#010101",
    capabilities: ["Fetch trends", "Get video data", "Creator analytics"],
    docsUrl: "https://developers.tiktok.com",
  },
  {
    service: "reddit",
    name: "Reddit",
    category: "Social",
    description: "Read posts, search subreddits, fetch trending content",
    authMethod: "api_key" as const,
    keyLabel: "Reddit Client ID:Secret (from App settings)",
    extraFields: [
      {
        key: "chatId",
        label: "Default Subreddit to monitor",
        placeholder: "technology",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#FF4500",
    capabilities: ["Search posts", "Read subreddits", "Fetch trending"],
    docsUrl: "https://www.reddit.com/prefs/apps",
  },
  {
    service: "facebook",
    name: "Facebook",
    category: "Social",
    description: "Post content to pages, read page insights",
    authMethod: "api_key" as const,
    keyLabel: "Facebook Page Access Token",
    color: "#1877F2",
    capabilities: ["Post to page", "Read page insights", "Schedule posts"],
    docsUrl: "https://developers.facebook.com/tools/explorer",
  },
  // ── Messaging ────────────────────────────────────────────────────────────
  {
    service: "whatsapp",
    name: "WhatsApp",
    category: "Messaging",
    description: "Send messages and templates via WhatsApp Business API",
    authMethod: "api_key" as const,
    keyLabel: "Meta WhatsApp Cloud API Access Token",
    extraFields: [
      {
        key: "phoneNumberId",
        label: "Phone Number ID (from Meta Business > WhatsApp)",
        placeholder: "1234567890123456",
        type: "text",
      },
      {
        key: "webhookToken",
        label: "Webhook Verify Token (you define this — paste in Meta Platform too)",
        placeholder: "my_secret_verify_token",
        type: "text",
      },
      {
        key: "chatId",
        label: "Recipient Phone Number (E.164 format)",
        placeholder: "+919876543210",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#25D366",
    capabilities: ["Send messages", "Use templates", "Receive messages via webhook"],
    docsUrl: "https://developers.facebook.com/docs/whatsapp",
  },
  // ── Marketing & Email ─────────────────────────────────────────────────────
  {
    service: "mailchimp",
    name: "Mailchimp",
    category: "Marketing",
    description: "Manage email lists, send campaigns, track subscribers",
    authMethod: "api_key" as const,
    keyLabel: "Mailchimp API Key",
    color: "#FFE01B",
    capabilities: ["Send campaigns", "Manage subscribers", "Track opens"],
    docsUrl: "https://mailchimp.com/developer/marketing/api/",
  },
  {
    service: "sendgrid",
    name: "SendGrid",
    category: "Marketing",
    description: "Send transactional emails and manage campaigns",
    authMethod: "api_key" as const,
    keyLabel: "SendGrid API Key (SG.xxx)",
    extraFields: [
      {
        key: "chatId",
        label: "Recipient Email Address",
        placeholder: "you@example.com",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#1A82E2",
    capabilities: ["Send emails", "Track delivery", "Manage templates"],
    docsUrl: "https://app.sendgrid.com/settings/api_keys",
  },
  {
    service: "resend",
    name: "Resend",
    category: "Marketing",
    description: "Modern email API for developers — fast and reliable",
    authMethod: "api_key" as const,
    keyLabel: "Resend API Key (re_xxx)",
    extraFields: [
      {
        key: "chatId",
        label: "Recipient Email Address",
        placeholder: "you@example.com",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#000000",
    capabilities: ["Send emails", "Use React templates", "Track events"],
    docsUrl: "https://resend.com/api-keys",
  },
  // ── Payment & Commerce ────────────────────────────────────────────────────
  {
    service: "stripe",
    name: "Stripe",
    category: "Payment",
    description: "Read payments, create invoices, manage customers",
    authMethod: "api_key" as const,
    keyLabel: "Stripe Secret Key (sk_live_... or sk_test_...)",
    color: "#635BFF",
    capabilities: ["Read payments", "Create invoices", "Manage customers"],
    docsUrl: "https://dashboard.stripe.com/apikeys",
  },
  {
    service: "shopify",
    name: "Shopify",
    category: "Payment",
    description: "Read orders, manage products and customers in your store",
    authMethod: "api_key" as const,
    keyLabel: "Shopify Admin API Access Token",
    color: "#96BF48",
    capabilities: ["Read orders", "Manage products", "Update inventory"],
    docsUrl: "https://shopify.dev/docs/api/admin-rest",
  },
  {
    service: "paypal",
    name: "PayPal",
    category: "Payment",
    description: "Read transactions, create invoices, check balances",
    authMethod: "api_key" as const,
    keyLabel: "PayPal Client ID:Secret (REST API)",
    color: "#00457C",
    capabilities: ["Read transactions", "Create invoices", "Refunds"],
    docsUrl: "https://developer.paypal.com/dashboard/applications",
  },
  // ── CRM ─────────────────────────────────────────────────────────────────
  {
    service: "hubspot",
    name: "HubSpot",
    category: "CRM",
    description: "Create contacts, update deals, log notes",
    authMethod: "api_key" as const,
    keyLabel: "HubSpot Private App Token",
    extraFields: [
      {
        key: "chatId",
        label: "Contact ID to associate notes with (optional)",
        placeholder: "12345678",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#FF7A59",
    capabilities: ["Create notes", "Create contacts", "Log activity"],
    docsUrl: "https://app.hubspot.com/private-apps",
  },
  {
    service: "salesforce",
    name: "Salesforce",
    category: "CRM",
    description: "Read leads, update opportunities, create cases",
    authMethod: "api_key" as const,
    keyLabel: "Salesforce Connected App Access Token",
    color: "#00A1E0",
    capabilities: ["Read leads", "Update opportunities", "Create cases"],
    docsUrl: "https://developer.salesforce.com/docs/atlas.en-us.api_rest.meta/api_rest",
  },
  {
    service: "pipedrive",
    name: "Pipedrive",
    category: "CRM",
    description: "Manage deals, contacts, and sales pipelines",
    authMethod: "api_key" as const,
    keyLabel: "Pipedrive API Token",
    color: "#26292C",
    capabilities: ["Manage deals", "Add contacts", "Track pipeline"],
    docsUrl: "https://app.pipedrive.com/settings/api",
  },
  // ── Productivity ─────────────────────────────────────────────────────────
  {
    service: "sheets",
    name: "Google Sheets",
    category: "Productivity",
    description: "Read and write spreadsheet data",
    authMethod: "api_key" as const,
    keyLabel: "Google Service Account JSON (paste stringified JSON)",
    extraFields: [
      {
        key: "chatId",
        label: "Spreadsheet ID (from sheet URL) — optionally append /SheetName",
        placeholder: "1BxiMVs0XRA5nFMdKvBdBZjgmUUqptlbs74OgVE2upms",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#34A853",
    capabilities: ["Append rows", "Write rows", "Create sheets"],
    docsUrl: "https://developers.google.com/sheets/api",
  },
  {
    service: "notion",
    name: "Notion",
    category: "Productivity",
    description: "Create pages, update databases, manage content",
    authMethod: "api_key" as const,
    keyLabel: "Notion Integration Token (secret_xxx)",
    extraFields: [
      {
        key: "chatId",
        label: "Database ID or Page ID to write results to",
        placeholder: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#000000",
    capabilities: ["Create pages", "Update databases", "Search content"],
    docsUrl: "https://www.notion.so/my-integrations",
  },
  {
    service: "airtable",
    name: "Airtable",
    category: "Productivity",
    description: "Read and write records in your Airtable bases",
    authMethod: "api_key" as const,
    keyLabel: "Airtable Personal Access Token",
    extraFields: [
      {
        key: "chatId",
        label: "Base ID / Table — format: appXXXXXXXX/TableName",
        placeholder: "appXXXXXXXXXXXXXX/AutoFlow Results",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#FCB400",
    capabilities: ["Create records", "Read records", "Search base"],
    docsUrl: "https://airtable.com/create/tokens",
  },
  {
    service: "trello",
    name: "Trello",
    category: "Productivity",
    description: "Create cards, manage boards, update lists",
    authMethod: "api_key" as const,
    keyLabel: "Trello API Key:Token",
    color: "#0052CC",
    capabilities: ["Create cards", "Manage boards", "Move cards"],
    docsUrl: "https://trello.com/power-ups/admin",
  },
  {
    service: "asana",
    name: "Asana",
    category: "Productivity",
    description: "Create tasks, update projects, manage teams",
    authMethod: "api_key" as const,
    keyLabel: "Asana Personal Access Token",
    color: "#FF5263",
    capabilities: ["Create tasks", "Update projects", "Assign work"],
    docsUrl: "https://app.asana.com/0/my-apps",
  },
  {
    service: "linear",
    name: "Linear",
    category: "Productivity",
    description: "Create issues, update sprints, manage engineering cycles",
    authMethod: "api_key" as const,
    keyLabel: "Linear API Key",
    color: "#5E6AD2",
    capabilities: ["Create issues", "Update sprints", "Manage cycles"],
    docsUrl: "https://linear.app/settings/api",
  },
  {
    service: "jira",
    name: "Jira",
    category: "Productivity",
    description: "Create tickets, update issues, manage sprints",
    authMethod: "api_key" as const,
    keyLabel: "Jira API Token (user@domain:token)",
    color: "#0052CC",
    capabilities: ["Create tickets", "Update issues", "Read sprints"],
    docsUrl: "https://id.atlassian.com/manage-profile/security/api-tokens",
  },
  // ── Analytics ────────────────────────────────────────────────────────────
  {
    service: "google-analytics",
    name: "Google Analytics",
    category: "Analytics",
    description: "Fetch page views, sessions, conversions, and more",
    authMethod: "api_key" as const,
    keyLabel: "Google Analytics Data API Key / Service Account",
    color: "#F9AB00",
    capabilities: ["Fetch page views", "Sessions data", "Conversion rates"],
    docsUrl: "https://developers.google.com/analytics/devguides/reporting/data/v1",
  },
  {
    service: "mixpanel",
    name: "Mixpanel",
    category: "Analytics",
    description: "Track user events, funnels, and retention metrics",
    authMethod: "api_key" as const,
    keyLabel: "Mixpanel Service Account Secret",
    color: "#7856FF",
    capabilities: ["Track events", "Funnel analysis", "Retention data"],
    docsUrl: "https://developer.mixpanel.com/reference/service-accounts",
  },
  // ── Support ──────────────────────────────────────────────────────────────
  {
    service: "zendesk",
    name: "Zendesk",
    category: "Support",
    description: "Create tickets, update customers, manage support queues",
    authMethod: "api_key" as const,
    keyLabel: "Zendesk API Token (email/token:api_token)",
    color: "#03363D",
    capabilities: ["Create tickets", "Update users", "Read queues"],
    docsUrl: "https://developer.zendesk.com/api-reference",
  },
  {
    service: "intercom",
    name: "Intercom",
    category: "Support",
    description: "Send in-app messages, manage contacts and conversations",
    authMethod: "api_key" as const,
    keyLabel: "Intercom Access Token",
    color: "#1F8DED",
    capabilities: ["Send messages", "Manage contacts", "Track conversations"],
    docsUrl: "https://app.intercom.com/a/developer-signup",
  },
  // ── Developer ────────────────────────────────────────────────────────────
  {
    service: "github",
    name: "GitHub",
    category: "Developer",
    description: "Read repos, create issues, manage pull requests",
    authMethod: "api_key" as const,
    keyLabel: "GitHub Personal Access Token",
    extraFields: [
      {
        key: "chatId",
        label: "Repository (owner/repo)",
        placeholder: "yourusername/your-repo",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#24292E",
    capabilities: ["Create issues", "Read PRs", "Push code"],
    docsUrl: "https://github.com/settings/tokens",
  },
  {
    service: "openai",
    name: "OpenAI",
    category: "Developer",
    description: "Call GPT-4, DALL-E, Whisper, and Embeddings APIs",
    authMethod: "api_key" as const,
    keyLabel: "OpenAI API Key (sk-...)",
    color: "#10A37F",
    capabilities: ["GPT-4 generation", "Image generation", "Embeddings"],
    docsUrl: "https://platform.openai.com/api-keys",
  },
  {
    service: "newsapi",
    name: "News API",
    category: "Developer",
    description: "Fetch live news articles from 80,000+ sources worldwide",
    authMethod: "api_key" as const,
    keyLabel: "News API Key",
    color: "#D9232D",
    capabilities: ["Top headlines", "Search articles", "Filter by source"],
    docsUrl: "https://newsapi.org/register",
  },
  {
    service: "weatherapi",
    name: "WeatherAPI",
    category: "Developer",
    description: "Get real-time weather, forecasts, and historical data",
    authMethod: "api_key" as const,
    keyLabel: "WeatherAPI Key",
    extraFields: [
      {
        key: "chatId",
        label: "Default Location (city, ZIP, or lat,lon)",
        placeholder: "London",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#0F6FD7",
    capabilities: ["Current weather", "7-day forecast", "Historical data"],
    docsUrl: "https://www.weatherapi.com/my",
  },
  {
    service: "coingecko",
    name: "CoinGecko",
    category: "Developer",
    description: "Live crypto prices, market caps, and exchange data",
    authMethod: "api_key" as const,
    keyLabel: "CoinGecko Demo or Pro API Key",
    color: "#8DC63F",
    capabilities: ["Crypto prices", "Market caps", "Exchange data"],
    docsUrl: "https://www.coingecko.com/api/pricing",
  },
  // ── Data ─────────────────────────────────────────────────────────────────
  {
    service: "meta-ads",
    name: "Meta Ads",
    category: "Marketing",
    description: "Read campaign insights, ad spend, and performance metrics from Meta Ads Manager",
    authMethod: "api_key" as const,
    keyLabel: "Meta Personal Access Token (from Meta Business > System Users or your profile)",
    extraFields: [
      {
        key: "chatId",
        label: "Ad Account ID (act_XXXXXXXXXXXXXXXXX)",
        placeholder: "act_123456789012345",
        type: "text",
      },
    ] as { key: string; label: string; placeholder: string; type?: string }[],
    color: "#1877F2",
    capabilities: ["Campaign insights", "Ad spend", "CTR & CPC metrics"],
    docsUrl: "https://developers.facebook.com/docs/marketing-api",
  },
  {
    service: "custom",
    name: "Custom API",
    category: "Custom",
    description: "Call any HTTP API with custom authorization headers",
    authMethod: "api_key" as const,
    keyLabel: "API Key (sent as Authorization: Bearer header)",
    color: "#6366F1",
    capabilities: ["HTTP GET", "HTTP POST", "Custom headers"],
    docsUrl: "",
  },
] as const;

export type ServiceId = (typeof INTEGRATIONS)[number]["service"];
